version: '2'

services:
    core:
        build: ./quassel-core/
        ports:
            - "49153:4242"
        # named volume corresponding to data-only-container
        volumes:
            - quassel:/var/lib/quassel

volumes:
    quassel:
